### ISSUE TITLE
smhi-forecast card reports error

### ISSUE THREAD

**Issue by Davst** [helto4real/lovelace-custom-cards#5]
Tried to use this custom card, but I get:
http://192.168.1.2:8123/community_plugin/smhi-forecast-card/smhi-forecast-card.js:29:41 Uncaught TypeError: Cannot set property 'getWindSpeed' of null

**Comment by helto4real** [comment]
@Davst I no longer support that card. If you need the SMHI to work wih m/s I recommend this https://github.com/helto4real/weather-card-mod

Sorry for your inconvenience.
